name: ClaimMessenger
version: '1.0.0'
main: me.justahuman.claimmessenger.ClaimMessenger
api-version: '1.20'
load: POSTWORLD
authors: [ JustAHuman ]
description: A plugin sending clients claim information for map mods such as JourneyMap and Xaero's World/Mini Map.
softdepend: [ HuskTowns, GriefPrevention, Lands, Towny ]